### PR TITLE
updated response handler

### PR DESCRIPTION
**Pull request by ExtraLime**
The response handler now handles the sleeping when encountering errors. changed sleep times to 6 and 65 for 502 and 429.

### CODE REVIEW

**Comment by KonradIT** [comment]
Hi, maybe that 65 sleep could be a __init__ variable?

**Comment by ExtraLime** [comment]
I thought about that, but it would need further constraints. Through my tests, I find that 60 seconds is the minimum pause required on 429 to not throw. Regardless, I'm not opposed to it being a var.

**Comment by KonradIT** [comment]
Merging, by the way, in the next PRs you make, use `logging` since I will switch Parler/__init__.py to it and use debug flags to make it silent or not.

**Comment by ExtraLime** [comment]
Will do. Thanks

**Pull request merged**
